<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>Ogx.IdentityService.Test.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.8.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Ogx.IdentityService.Http.Host\Ogx.IdentityService.Http.Host.csproj" />
    </ItemGroup>

</Project>
